project(asterisk-all)
set    (CMAKE_C_STANDARD 11)

if    (UNIX AND NOT APPLE)
    if   (NOT EXISTS /usr/bin/git)
        message("[asterisk] Git Installation is required for the initialization.")
        message(SEND_ERROR "Abort")
    endif()

    if   (NOT EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/lib/crisp)
        message        ("[asterisk] Clone Crisp to ./lib/crisp...")
        execute_process(COMMAND git clone https://github.com/gunnerDgd/crisp WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/lib)
    endif()
elseif(WIN32)
    set (GIT_PATH "C:/Program Files/Git/bin/git.exe")
    if   (NOT EXISTS ${GIT_PATH})
        message("[asterisk] Git Installation is required for the initialization.")
        message(SEND_ERROR "Abort")
    endif()

    if   (NOT EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/lib/crisp)
        message        ("[asterisk] Clone Crisp to ./lib/crisp...")
        execute_process(COMMAND git clone https://github.com/gunnerDgd/crisp WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/lib)
    endif()
endif ()

if     (PRESET_ARCH_X86_64)
    add_compile_definitions(PRESET_ARCH_X86_64)
    add_compile_definitions(PRESET_ARCH_BIT=64)
    add_compile_definitions(PRESET_ARCH_ENDIAN_LITTLE)

    set(PRESET_ARCH_ENDIAN_LITTLE on)
    set(PRESET_ARCH_ENDIAN_BIG    off)

    set(PRESET_ARCH_X86_64 on)
    set(PRESET_ARCH_BIT 64)
elseif (PRESET_ARCH_X86)
    add_compile_definitions(PRESET_ARCH_X86)
    add_compile_definitions(PRESET_ARCH_BIT=32)
    add_compile_definitions(PRESET_ARCH_ENDIAN_LITTLE)

    set(PRESET_ARCH_ENDIAN_LITTLE on)
    set(PRESET_ARCH_ENDIAN_BIG    off)

    set(PRESET_ARCH_X86 on)
    set(PRESET_ARCH_BIT 32)
endif()

if     ("${CMAKE_C_COMPILER_ID}" MATCHES  "Clang")
    add_compile_definitions(PRESET_COMPILER_CLANG)
    add_compile_definitions(PRESET_CALL_SYSV)

    set(PRESET_COMPILER_CLANG on)
    set(PRESET_CALL_SYSV      on)
elseif ("${CMAKE_C_COMPILER_ID}" STREQUAL "GNU")
    add_compile_definitions(PRESET_COMPILER_GCC)
    add_compile_definitions(PRESET_CALL_SYSV)

    set(PRESET_COMPILER_GCC on)
    set(PRESET_CALL_SYSV    on)
elseif ("${CMAKE_C_COMPILER_ID}" STREQUAL "Intel")
    add_compile_definitions(PRESET_COMPILER_INTEL)
    add_compile_definitions(PRESET_CALL_SYSV)

    set(PRESET_COMPILER_INTEL on)
    set(PRESET_CALL_SYSV      on)
elseif ("${CMAKE_C_COMPILER_ID}" STREQUAL "MSVC")
    add_compile_definitions(PRESET_COMPILER_MSVC)
    add_compile_definitions(PRESET_CALL_VECTORCALL)

    set(PRESET_COMPILER_MSVC   on)
    set(PRESET_CALL_VECTORCALL on)
endif()

if    (WIN32)
    add_compile_definitions(PRESET_WIN32)
    set(PRESET_WIN32 on)
elseif(UNIX AND NOT APPLE)
    add_compile_definitions(PRESET_LINUX)
    set(PRESET_LINUX on)
endif ()

include_directories(lib/crisp/include)
add_subdirectory   (lib)
add_subdirectory   (src)
add_subdirectory   (example)