cmake_minimum_required(VERSION 3.14)
project(asterisk-all)

if    (NOT ${CMAKE_SOURCE_DIR} STREQUAL ${CMAKE_CURRENT_SOURCE_DIR})
    if    (UNIX AND NOT APPLE)
        if   (NOT EXISTS /usr/bin/git)
            message("[asterisk] Git Installation is required for the initialization.")
            message(SEND_ERROR "Abort")
        endif()

        if   (NOT EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/lib/crisp)
            message        ("[asterisk] Clone Crisp to ./lib/crisp...")
            execute_process(COMMAND git clone https://github.com/gunnerDgd/crisp WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/lib)
        endif()
    elseif(WIN32)
        set (GIT_PATH "C:/Program Files/Git/bin/git.exe")
        if   (NOT EXISTS ${GIT_PATH})
            message("[asterisk] Git Installation is required for the initialization.")
            message(SEND_ERROR "Abort")
        endif()

        if   (NOT EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/lib/crisp)
            message        ("[asterisk] Clone Crisp to ./lib/crisp...")
            execute_process(COMMAND git clone https://github.com/gunnerDgd/crisp WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/lib)
        endif()
    endif ()

    include (${CMAKE_CURRENT_SOURCE_DIR}/lib/crisp/cmake/preset.cmake)
    preset_arch    ()
    preset_bit     ()
    preset_compiler()
    preset_endian  ()
    preset_os      ()

    enable_collections()
    enable_libc       ()
endif ()

include_directories(lib/crisp/include)
add_subdirectory   (lib)
add_subdirectory   (src)
add_subdirectory   (example)